# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Get branch name
      #   id: branch-name
      #   uses: ./.github/workflows/branch-actions

      - name: Get branch name outputs
        run: |
          BASE_REF=$(printf "%q" "${{ github.base_ref }}")
          HEAD_REF=$(printf "%q" "${{ github.head_ref }}")
          REF=$(printf "%q" "${{ github.ref }}")

          BASE_REF=${BASE_REF/refs\/heads\//}
          HEAD_REF=${HEAD_REF/refs\/heads\//}

          echo "$(eval printf "%s" "$BASE_REF")"
          echo "$(eval printf "%s" "$HEAD_REF")"

          REF_BRANCH=${REF/refs\/pulls}
          echo "$(eval printf "%s" "$REF_BRANCH")"
          REF_BRANCH=${REF_BRANCH/refs\/heads\//}
          echo "$(eval printf "%s" "$REF_BRANCH")"
        shell: bash
